using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwInvDocDwithoutUser
    {
        public int InvDocDSi { get; set; }
        public int InvDocHSi { get; set; }
        public int InvGdsSi { get; set; }
        public int? InvUntSi { get; set; }
        public double? InvDocDQty { get; set; }
        public decimal InvDocDPrice { get; set; }
        public decimal InvDocDTotal { get; set; }
        public string InvDocDTp { get; set; }
        public string InvGdsCu { get; set; }
        public string InvGdsTp { get; set; }
        public string InvUntCu { get; set; }
        public string InvUntTp { get; set; }
        public string CtbCostCu { get; set; }
        public string CtbCostTp { get; set; }
        public string CtbProjectCu { get; set; }
        public string CtbProjectTp { get; set; }
        public int? InvDocHCu { get; set; }
        public string InvDocHDs { get; set; }
        public string InvDocHReference { get; set; }
        public bool? InvDocHDefinite { get; set; }
        public int? InvDocTypSi { get; set; }
        public int? InvInvtSi { get; set; }
        public int? PurVndrSi { get; set; }
        public string InvDocTypTp { get; set; }
        public string InvDocTypTp2 { get; set; }
        public string PurVndrCu { get; set; }
        public string PurVndrTp { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public int? PerPersonnelSi { get; set; }
        public string PerPersonnelCu { get; set; }
        public string PerPersonnelTp { get; set; }
        public int? InvGdsGrpSi { get; set; }
        public int? InvInvtSi2 { get; set; }
        public int? InvDocHRfrncTyp { get; set; }
        public int? SalCustSi { get; set; }
        public string SalCustCu { get; set; }
        public string SalCustTp { get; set; }
        public byte InvDocDstsSi { get; set; }
        public string InvDocDstsTp { get; set; }
        public int? AccLmSiInvt { get; set; }
        public int? AccLtSiInvt { get; set; }
        public int? PurVndrAccMSi { get; set; }
        public int? PurVndrAccTSi { get; set; }
        public int? AccLmSiInvt2 { get; set; }
        public int? AccLtSiInvt2 { get; set; }
        public int? AccLmSi { get; set; }
        public int? AccLtSi { get; set; }
        public int? CtbCostSi { get; set; }
        public int? CtbProjectSi { get; set; }
        public int? InvGdsTypSi { get; set; }
        public int? InvDocHSiParent { get; set; }
        public int? AccLmSiHdr { get; set; }
        public string InvGdsTypTp { get; set; }
        public DateTime? InvDocDExpireDate { get; set; }
        public string InvDocHTp { get; set; }
        public double InvDocDQtyOriginal { get; set; }
        public double? InvDocDQty2 { get; set; }
        public string InvUntCuOriginal { get; set; }
        public string InvUntTpOriginal { get; set; }
        public int? InvDocHSi2 { get; set; }
        public string InvGdsTechNo { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CuAccT { get; set; }
        public string TpAccT { get; set; }
        public string CuAccM { get; set; }
        public string TpAccM { get; set; }
        public int? SiAccM { get; set; }
        public int? InvDocHCu2 { get; set; }
        public DateTime? InvDocHDm { get; set; }
        public string InvDocDSerialKey { get; set; }
        public decimal? InvDocDTotalC { get; set; }
        public string InvDocHExpNo { get; set; }
        public int? CtbCurncySi { get; set; }
        public double? ExchangeRate { get; set; }
        public decimal? InvDocDPriceC { get; set; }
        public string CtbPrpVluValue { get; set; }
        public string InvDocDDesc { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? SalCustGrpSi { get; set; }
        public string InvDocDExpNo { get; set; }
        public int? SalExportPrmHSi { get; set; }
        public int? PurVndrGrpSi { get; set; }
        public string CtbCurncyTp { get; set; }
        public bool? TempDoc { get; set; }
        public int? InvDocHGood { get; set; }
        public int? InvControlGdsSi { get; set; }
        public int? InvExportPrmHSi { get; set; }
        public decimal? InvDocDTotalBs { get; set; }
        public int? SalCustAccTSi { get; set; }
        public string BarNumber { get; set; }
        public int? InvDocTmpDSi { get; set; }
        public string DescDriver { get; set; }
        public string InvDocHDlvLoc { get; set; }
        public string InvDocHDrivername { get; set; }
        public int? SalDriverSi { get; set; }
        public string SalDriverTp { get; set; }
        public int? InvDocTmpHSi { get; set; }
        public string InvDocHDlvBuy { get; set; }
        public string InvDocHCarNo { get; set; }
        public string InvGdsToInvShelf { get; set; }
        public double? InvDocDFinalCostPrice { get; set; }
        public int? SalCustAccLmSi { get; set; }
    }
}
