using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwPerPrsnlD
    {
        public int PerPrsnlSi { get; set; }
        public string PerPrsnlCu { get; set; }
        public string PerPrsnlTp { get; set; }
        public string PerPrsnlFname { get; set; }
        public string PerPrsnlLname { get; set; }
        public bool PerPrsnlAct { get; set; }
        public string PerPrsnlAct1 { get; set; }
        public string PerPrsnlDPname { get; set; }
        public string PerPrsnlDIdno { get; set; }
        public string PerPrsnlDIdloc { get; set; }
        public string PerPrsnlDBrtDte { get; set; }
        public bool? PerPrsnlDMarid { get; set; }
        public string PerPrsnlDmarid1 { get; set; }
        public byte? PerPrsnlDChld { get; set; }
        public string PerPrsnlDSldr { get; set; }
        public string PerPrsnlDEdu { get; set; }
        public string PerPrsnlDEmpDte { get; set; }
        public string PerPrsnlDWrkBgnDte { get; set; }
        public string PerPrsnlDWrkEndDte { get; set; }
        public byte? PerPrsnlDSex { get; set; }
        public string PerPrsnlDsex1 { get; set; }
        public bool? PerPrsnlDFrgn { get; set; }
        public string PerPrsnlDfrgn1 { get; set; }
        public string PerPrsnlDEmail { get; set; }
        public string PerPrsnlDUrl { get; set; }
        public string PerPrsnlDTel1 { get; set; }
        public string PerPrsnlDTel2 { get; set; }
        public string PerPrsnlDFax { get; set; }
        public string PerPrsnlDAdrs { get; set; }
        public string PerPrsnlDBnkName { get; set; }
        public string PerPrsnlDBnkBrnch { get; set; }
        public string PerPrsnlDBnkAccNo { get; set; }
        public string PerPrsnlDBnkAccTyp { get; set; }
        public string InsrncFname { get; set; }
        public string InsrncLname { get; set; }
        public string InsrncDname { get; set; }
        public string InsrncIdno { get; set; }
        public string InsrncIdplc { get; set; }
        public string InsrncNat { get; set; }
        public string InsrncOcp { get; set; }
        public string InsrncNo { get; set; }
        public string PerPrsnlDIddte { get; set; }
        public byte? PerInsrncGrpSi { get; set; }
        public string PerPrsnlIdNatCode { get; set; }
        public string InsrncOcpcode { get; set; }
        public DateTime? PerPrsnlDBuyBak { get; set; }
        public string PerInsrncGrpTp { get; set; }
        public string PerPrsnlDUniverCity { get; set; }
        public string PerPrsnlDMajor { get; set; }
        public int? AccLtSi { get; set; }
        public int? PerLocSi { get; set; }
        public int? BankAccountNo { get; set; }
        public string PerPrsnlDPostCode { get; set; }
        public int? PerPrsnlDHistoryJob { get; set; }
        public int? PerTaxGrpSi { get; set; }
        public int? PereEducateSi { get; set; }
        public int? PerMajorSi { get; set; }
        public int? PerExemptSi { get; set; }
        public int? PerInterNationalSi { get; set; }
        public int? PerPrsnlDInsureType { get; set; }
        public string PerPrsnlDCountry { get; set; }
        public string PerPrsnlDIdentityJob { get; set; }
        public int? PerPrsnlDGroupCode { get; set; }
        public string PerPrsnlDJobPlace { get; set; }
        public string PerPrsnlDTimeWorkAcc { get; set; }
        public string PerPrsnlDTimeInwar { get; set; }
        public string PerPrsnlDEmpStatus { get; set; }
        public string PerPrsnlDTypJob { get; set; }
        public string PerPrsnlDLiberal { get; set; }
        public string PerPrsnlDReligion { get; set; }
        public string PerPrsnlDPlcBrth { get; set; }
        public int? PerPrsnlDExpert { get; set; }
        public string PerPrsnlDhome { get; set; }
        public int? PerPrsnlDHome1 { get; set; }
        public string PerPrsnlDHardCode { get; set; }
        public int? PerInsrnPromiseSi { get; set; }
        public int? PerPrsnlDPhoto { get; set; }
        public string PereEducateCu { get; set; }
        public string PereEducateTp { get; set; }
        public string PerPrsnlDPost { get; set; }
        public string PerInsurTypeCu { get; set; }
        public string PerInsurTypeTp { get; set; }
        public string PerPrsnlDPostName { get; set; }
        public string PerPrsnlDPlaceOffice { get; set; }
        public int? PerPlaceOfficeStatusSi { get; set; }
        public string PerPlaceOfficeStatusTp { get; set; }
        public string PerPlaceOfficeStatusCu { get; set; }
        public int? PeremployeeStatusSi { get; set; }
        public string PeremployeeStatusCu { get; set; }
        public string PeremployeeStatusTp { get; set; }
        public int? PerPaidTypeSi { get; set; }
        public int? CtbCurncySi { get; set; }
        public double? ExchangeRate { get; set; }
        public int? PerVehicleFlagSi { get; set; }
        public int? PerFurnitureFlagSi { get; set; }
        public int? PerCurencySi { get; set; }
        public int? PerContractTypSi { get; set; }
        public string PerInsurnceName { get; set; }
        public string PerContractTypCu { get; set; }
        public string PerContractTypTp { get; set; }
        public string PerPrsnlDlocTp { get; set; }
        public string PerMajorCu { get; set; }
        public string PerMajorTp { get; set; }
        public string PerExemptCu { get; set; }
        public string PerExemptTp { get; set; }
        public string PerInterNationalCu { get; set; }
        public string PerInterNationalTp { get; set; }
        public string PerPaidTypeCu { get; set; }
        public string PerPaidTypeTp { get; set; }
        public string PerTaxGrpCu { get; set; }
        public string PerTaxGrpTp { get; set; }
        public int? PerPrsnlDSponsorShipNo { get; set; }
        public int? PerPrsnlDTypeCmd { get; set; }
        public string PerPrsnlDJobType { get; set; }
        public string PerPrsnlIdPassportCode { get; set; }
        public bool? PerPrsnlNotBimeh { get; set; }
        public string PerInsrnpromiseTp { get; set; }
        public string PerInsrnpromiseCu { get; set; }
        public string CuAcc { get; set; }
        public string TpAcc { get; set; }
        public string InsrncOcptp { get; set; }
    }
}
