using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalRetInvcD
    {
        public int SalRetInvcDSi { get; set; }
        public int SalRetInvcHSi { get; set; }
        public int InvGdsSi { get; set; }
        public int? SalRetInvcDRow { get; set; }
        public double SalRetInvcDQty { get; set; }
        public decimal SalRetInvcDUntPrc { get; set; }
        public decimal SalRetInvcDTotal { get; set; }
        public string InvGdsCu { get; set; }
        public string InvGdsTp { get; set; }
        public int? SalRetInvcHCu { get; set; }
        public string SalRetInvcHDs { get; set; }
        public string SalRetInvcHTp { get; set; }
        public short? SalRetInvcHRfrncTyp { get; set; }
        public string SalRetInvcHReference { get; set; }
        public decimal? SalRetInvcHPrcSumTotal { get; set; }
        public decimal? SalRetInvcHPrcInc { get; set; }
        public decimal? SalRetInvcHPrcDec { get; set; }
        public decimal? SalRetInvcHPrcTotal { get; set; }
        public int? SalCustSi { get; set; }
        public int? SalBrnchSi { get; set; }
        public int? SalIntrmdSi { get; set; }
        public int? InvInvtSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public string SalIntrmdTp { get; set; }
        public string SalCustCu { get; set; }
        public string SalCustTp { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public string SalRetInvcDTp { get; set; }
        public bool? SalRetInvcHAccDoc { get; set; }
        public int? InvUntSi { get; set; }
        public string InvUntCu { get; set; }
        public string InvUntTp { get; set; }
        public double? SalRetInvcDQty2 { get; set; }
        public int? SalGdsAccAccMSi { get; set; }
        public int? SalGdsAccAccTSi { get; set; }
        public string SalRetInvcHStmpCus { get; set; }
        public DateTime? SalRetInvcHStmpCdt { get; set; }
        public string SalRetInvcHStmpMus { get; set; }
        public DateTime? SalRetInvcHStmpMdt { get; set; }
        public int? SalRegionSi { get; set; }
        public string SalRegionTp { get; set; }
        public int? SalRetInvcHDsMonth { get; set; }
        public int? SalCustGrpSi { get; set; }
        public int? CtbCurncySi { get; set; }
        public double? ExchangeRate { get; set; }
        public double? SalRetInvcDUntPrcC { get; set; }
        public decimal? SalRetInvcDTotalC { get; set; }
        public string CtbCurncyTp { get; set; }
        public int? InvGdsGrpSi { get; set; }
        public int? SalOprSi { get; set; }
        public string SalOprTp { get; set; }
        public double? SalOprDefaultValue { get; set; }
        public decimal? SalretInvcDPrcDec { get; set; }
        public decimal? SalretInvcDPrcInc { get; set; }
        public decimal? SalretInvcDPrcDec2 { get; set; }
        public decimal? SalretInvcDPrcInc2 { get; set; }
        public int? SalOprSi2 { get; set; }
        public string SalOprTp2 { get; set; }
        public double? SalOprDefaultValue2 { get; set; }
        public double? SalRetInvcDSumPrcDec { get; set; }
        public double? SalRetInvcDSumPrcInc { get; set; }
        public decimal? SalRetInvCdSumTotal { get; set; }
        public string InvGdsTechNo { get; set; }
        public int? SalOprSi3 { get; set; }
        public string SalOprTp3 { get; set; }
        public double? SalOprDefaultValue3 { get; set; }
        public decimal? SalretInvcDPrcDec3 { get; set; }
        public decimal? SalretInvcDPrcInc3 { get; set; }
        public string BatchNumberD { get; set; }
        public DateTime? SalRetInvcDExpiredate { get; set; }
        public string InvGdsIcntryTp { get; set; }
        public string InvGdsIcntryCu { get; set; }
        public bool? SalRetInvcDGiftOk { get; set; }
        public int? InvGdsIcratrSi { get; set; }
        public string InvGdsIcratrTp { get; set; }
        public string InvGdsIcratrCu { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? SalRetInvcHCu2 { get; set; }
        public short? SalCustCorporateTyp { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public int? SalCitySi { get; set; }
        public int? SalProvinceSi { get; set; }
        public int? InvGdsTypSi { get; set; }
        public string InvGdsTypTp { get; set; }
        public int? SalCustAccMSi { get; set; }
        public int? SalCustAccTSi { get; set; }
        public int? SalGdsRetAccAccCSi { get; set; }
        public int? SalGdsRetAccAccPSi { get; set; }
        public int? SiCost { get; set; }
        public string InvGdsToInvShelf { get; set; }
        public bool? SalRetInvcHCancelled { get; set; }
        public string BatchNumberH { get; set; }
        public int? SalTypSi { get; set; }
        public int? SalRespSi { get; set; }
        public string CtbAddrsEmail { get; set; }
        public string CtbAddrsModem { get; set; }
        public string CtbAddrsMobile { get; set; }
        public int? CtbCustVndrTypSi { get; set; }
        public int? SalCustStatusSi { get; set; }
        public int? SalEnterducedSi { get; set; }
        public int? SalCustActiveTypSi { get; set; }
        public int? SalRegionPathSi { get; set; }
        public int? SalvarietySi { get; set; }
        public int? SalDivisionSi { get; set; }
    }
}
