using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalInvcHtrS
    {
        public int SalInvcHSi { get; set; }
        public int? SalInvcHCu { get; set; }
        public string SalInvcHDs { get; set; }
        public string SalInvcHTp { get; set; }
        public short SalInvcHRfrncTyp { get; set; }
        public string SalInvcHReference { get; set; }
        public string SalInvcHDlvLoc { get; set; }
        public string SalInvcHRcvMthd { get; set; }
        public decimal SalInvcHPrcSumTotal { get; set; }
        public decimal? SalInvcHPrcSumTotalC { get; set; }
        public decimal SalInvcHPrcInc { get; set; }
        public decimal SalInvcHPrcDec { get; set; }
        public decimal SalInvcHPrcTotal { get; set; }
        public bool SalInvcHCancelled { get; set; }
        public int SalCustSi { get; set; }
        public int? SalBrnchSi { get; set; }
        public int? SalTypSi { get; set; }
        public int? SalIntrmdSi { get; set; }
        public int? InvInvtSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public string SalIntrmdTp { get; set; }
        public string SalTypCu { get; set; }
        public string SalTypTp { get; set; }
        public string SalCustTp { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public string CtbAddrsCity { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsPobox { get; set; }
        public string CtbAddrsOstan { get; set; }
        public string CtbAddrsShahrestan { get; set; }
        public string CtbAddrsFax { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public int? SalCustAccMSi { get; set; }
        public int? SalCustAccTSi { get; set; }
        public int? SalInvcHCu2 { get; set; }
        public bool SalInvcHAccDoc { get; set; }
        public bool SalInvcHPrcRcvd { get; set; }
        public string SalInvcHStmpCus { get; set; }
        public DateTime? SalInvcHStmpCdt { get; set; }
        public string SalInvcHStmpMus { get; set; }
        public DateTime? SalInvcHStmpMdt { get; set; }
        public string SalCustCu { get; set; }
        public string SalRespTp { get; set; }
        public string SalDlvrrTp { get; set; }
        public int? SalRespSi { get; set; }
        public int? SalDrvrSi { get; set; }
        public int? SalDlvrrSi { get; set; }
        public int? SalCustGrpSi { get; set; }
        public int? InvDocHSi { get; set; }
        public int? InvDocHAccMSi { get; set; }
        public bool? SalInvcHLock { get; set; }
        public int? InvDocHCu { get; set; }
        public string InvDocHDs { get; set; }
        public bool? InvDocHDefinite { get; set; }
        public int? SalRegionSi { get; set; }
        public string SalRegionTp { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? SalCustStatusSi { get; set; }
        public string SalDrvrTp { get; set; }
        public string SalDrvrTel { get; set; }
        public string SalDrvrAdrs { get; set; }
        public byte[] SalDrvrPhoto { get; set; }
        public int? AccLmSi { get; set; }
        public int? AccLtSi { get; set; }
        public int? SalCancleSi { get; set; }
        public int? SalGiftInvGdsSi { get; set; }
        public decimal? SalInvcHGiftTotal { get; set; }
        public int? SalContractHSi { get; set; }
        public int? Salprint { get; set; }
        public int? SalContractHCu { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public int? SalInvcHDsMonth { get; set; }
        public int? SalPreinvcHSi { get; set; }
        public int? SalPreInvcHCu { get; set; }
        public string SalInvcHDsMonthTp { get; set; }
        public bool? CtbAddrsDefault { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public string SalRegionPathTp { get; set; }
        public int? SalRegionPathSi { get; set; }
        public int? AccLmSi2 { get; set; }
        public byte? SalIntrmdValueTyp { get; set; }
        public decimal? SalIntrmdDefaultValue { get; set; }
        public string SalCancleTp { get; set; }
        public string BarNumber { get; set; }
        public string DescDriver { get; set; }
        public int? SalInvcHGood { get; set; }
        public string SalInvcHGoodTp { get; set; }
        public string AddrsSecondary { get; set; }
    }
}
