using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalInvcD
    {
        public int? SalInvcDSi { get; set; }
        public int? SalInvcHSi { get; set; }
        public int? InvGdsSi { get; set; }
        public int? SalInvcDRow { get; set; }
        public decimal? SalInvcDQty { get; set; }
        public decimal? SalInvcDUntPrc { get; set; }
        public decimal? SalInvcDTotal { get; set; }
        public string InvGdsCu { get; set; }
        public string InvGdsTp { get; set; }
        public string SalInvcDTp { get; set; }
        public int? SalGdsAccAccMSi { get; set; }
        public int? SalGdsAccAccTSi { get; set; }
        public string InvGdsTechNo { get; set; }
        public string SalInvcDRno { get; set; }
        public DateTime? SalInvcDRds { get; set; }
        public int? InvUntSi { get; set; }
        public string InvUntCu { get; set; }
        public string InvUntTp { get; set; }
        public double? SalInvcDQty2 { get; set; }
        public int? SalInvcHCu { get; set; }
        public string SalInvcHDs { get; set; }
        public decimal SalInvcHPrcSumTotal { get; set; }
        public decimal SalInvcHPrcInc { get; set; }
        public decimal SalInvcHPrcDec { get; set; }
        public decimal SalInvcHPrcTotal { get; set; }
        public bool SalInvcHCancelled { get; set; }
        public string SalInvcHTp { get; set; }
        public short SalInvcHRfrncTyp { get; set; }
        public string SalInvcHReference { get; set; }
        public string SalInvcHDlvLoc { get; set; }
        public string SalInvcHRcvMthd { get; set; }
        public int SalCustSi { get; set; }
        public int? SalBrnchSi { get; set; }
        public int? SalTypSi { get; set; }
        public int? SalIntrmdSi { get; set; }
        public int? InvInvtSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public string SalIntrmdTp { get; set; }
        public string SalTypCu { get; set; }
        public string SalTypTp { get; set; }
        public string SalCustTp { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public int? SalInvcHCu2 { get; set; }
        public bool SalInvcHAccDoc { get; set; }
        public string SalCustCu { get; set; }
        public string SalDrvrTp { get; set; }
        public string SalRespTp { get; set; }
        public string SalDlvrrTp { get; set; }
        public int? SalRespSi { get; set; }
        public int? SalDrvrSi { get; set; }
        public int? SalDlvrrSi { get; set; }
        public int? SalCustGrpSi { get; set; }
        public bool? SalInvcHLock { get; set; }
        public int? SalRegionSi { get; set; }
        public string SalRegionTp { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? SalCustStatusSi { get; set; }
        public string InvUntCu2 { get; set; }
        public string InvUntTp2 { get; set; }
        public double? SalOprDefaultValue { get; set; }
        public string SalOprTp { get; set; }
        public int? SalOprSi { get; set; }
        public double? SalInvcDPrcInc { get; set; }
        public double? SalInvcDPrcDec { get; set; }
        public decimal? SalInvCdSumTotal { get; set; }
        public string SalInvcHStmpCus { get; set; }
        public DateTime? SalInvcHStmpCdt { get; set; }
        public string SalInvcHStmpMus { get; set; }
        public DateTime? SalInvcHStmpMdt { get; set; }
        public int? SalContractHSi { get; set; }
        public int? SalCancleSi { get; set; }
        public int? SalGiftInvGdsSi { get; set; }
        public int? InvDocHAccMSi { get; set; }
        public bool? SalInvcDGiftOk { get; set; }
        public int? InvGdsGrpSi { get; set; }
        public int? SalInvcHDsMonth { get; set; }
        public string SalInvcHDsMonthTp { get; set; }
        public int? InvUntCount { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public double? ExchangeRate { get; set; }
        public int? CtbCurncySi { get; set; }
        public double? SalInvcDTotalC { get; set; }
        public double? SalInvcDUntPrcC { get; set; }
        public string CtbAddrsCity { get; set; }
        public string CtbCurncyTp { get; set; }
        public int? SalPreinvcHSi { get; set; }
        public bool? CtbAddrsDefault { get; set; }
        public int? SalPreInvcHCu { get; set; }
        public double? SalInvcDSumPrcInc { get; set; }
        public double? SalInvcDSumPrcDec { get; set; }
        public double? SalInvcDPrcInc2 { get; set; }
        public double? SalInvcDPrcDec2 { get; set; }
        public double? SalOprDefaultValue2 { get; set; }
        public string SalOprTp2 { get; set; }
        public int? SalOprSi2 { get; set; }
        public string CtbAddrsOstan { get; set; }
        public string CtbAddrsShahrestan { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public string SalRegionPathTp { get; set; }
        public int? SalRegionPathSi { get; set; }
        public string CtbPrpVluValue { get; set; }
        public string SalCancleTp { get; set; }
        public int? InvGdsTypSi { get; set; }
        public string InvGdsTypTp { get; set; }
        public string BarNumber { get; set; }
        public DateTime? SalInvcHDm { get; set; }
        public decimal? SalInvcHPrcSumTotalC { get; set; }
        public string CtbAddrsPobox { get; set; }
        public string CtbAddrsFax { get; set; }
        public int? SalCustAccMSi { get; set; }
        public int? SalCustAccTSi { get; set; }
        public int? SalOprSi3 { get; set; }
        public string SalOprTp3 { get; set; }
        public double? SalOprDefaultValue3 { get; set; }
        public double? SalInvcDPrcDec3 { get; set; }
        public double? SalInvcDPrcInc3 { get; set; }
        public string BatchNumberD { get; set; }
        public string SalInvcHPrcRcvdDt { get; set; }
        public short? SalCustCorporateTyp { get; set; }
        public string SalCustTitle { get; set; }
        public string SalCustCorporateTypTp { get; set; }
        public string InvGdsIcntryTp { get; set; }
        public string InvGdsIcntryCu { get; set; }
        public DateTime? SalInvcDExpiredate { get; set; }
        public string SalInvcHBarNo { get; set; }
        public string SalinvcHCarNo { get; set; }
        public string DescDriver { get; set; }
        public string SalInvcHPostCode { get; set; }
        public string SalInvcHCodeSharestan { get; set; }
        public string SalInvcHTel { get; set; }
        public string SalInvcHAddrsPur { get; set; }
        public string SalInvcHNamePur { get; set; }
        public string SalInvcHIno { get; set; }
        public string SalInvcHNationalCode { get; set; }
        public string SalInvcHFamilyPur { get; set; }
        public double? SalInvcDPurDebit { get; set; }
        public double? SalInvcDPurCredit { get; set; }
        public string SalInvcDPurDesc { get; set; }
        public int? SiAccT { get; set; }
        public int? SalInvcHGood { get; set; }
        public int? InvDocHCu { get; set; }
        public string InvDocHDs { get; set; }
        public decimal? InvDocDTotal { get; set; }
        public string InvGdsGrpCu { get; set; }
        public string InvGdsGrpTp { get; set; }
        public string InvGdsIcratrTp { get; set; }
        public string InvGdsIcratrCu { get; set; }
        public int? InvGdsIcratrSi { get; set; }
        public int? SiAccM { get; set; }
        public double? SalInvcDGrntCust { get; set; }
        public double? SalInvcDCoefficientCust { get; set; }
        public double? SalInvcDTotalGrantCust { get; set; }
        public double? SalInvcDGrntIntrmd { get; set; }
        public double? SalInvcDCoefficientintrmd { get; set; }
        public double? SalInvcDTotalGrantIntrmd { get; set; }
        public double? SalInvcHSumGrantCust { get; set; }
        public double? SalInvcHSumGrantIntrmd { get; set; }
        public double? Qty2 { get; set; }
        public int? SalCustActiveTypSi { get; set; }
        public int? CtbCustVndrTypSi { get; set; }
        public int? SalEnterducedSi { get; set; }
        public int? SalDivisionSi { get; set; }
        public int? SalvarietySi { get; set; }
        public int? SalCitySi { get; set; }
        public int? SalProvinceSi { get; set; }
        public int? AccLcSi { get; set; }
        public int? AccLpSi { get; set; }
        public int? SalDriverSi { get; set; }
        public string InvGdsCm { get; set; }
        public int? SalGdsAccAccCSi { get; set; }
        public int? SalGdsAccAccPSi { get; set; }
        public int? CtbAddrsNumber { get; set; }
        public int? SiCost { get; set; }
        public string InvGdsToInvShelf { get; set; }
        public DateTime? SalInvcDExpiredateSh { get; set; }
        public string InvGdsLname { get; set; }
        public double? SalDlvrrPercent { get; set; }
        public string SalInvcHStmpTime { get; set; }
        public string SalInvcHStmpTimeEdit { get; set; }
        public string SalDlvrrTpEn { get; set; }
    }
}
