using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalRequestD
    {
        public int? SalRequestHCu { get; set; }
        public string SalRequestHDs { get; set; }
        public string SalRequestHTp { get; set; }
        public decimal? SalRequestHPrcSumTotal { get; set; }
        public decimal? SalRequestHPrcSumTotalC { get; set; }
        public decimal? SalRequestHPrcInc { get; set; }
        public decimal? SalRequestHPrcDec { get; set; }
        public decimal? SalRequestHPrcTotal { get; set; }
        public string SalCustCu { get; set; }
        public int? SalCustSi { get; set; }
        public string SalCustTp { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public int? SalBrnchSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public int? SalIntrmdSi { get; set; }
        public string SalIntrmdTp { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public int? InvInvtSi { get; set; }
        public int? SalPreInvcHCu { get; set; }
        public string SalPreInvcHDs { get; set; }
        public int? SalRequestDRow { get; set; }
        public double SalRequestDQty { get; set; }
        public int InvGdsSi { get; set; }
        public int SalRequestHSi { get; set; }
        public decimal SalRequestDUntPrc { get; set; }
        public decimal SalRequestDTotal { get; set; }
        public string SalRequestDTp { get; set; }
        public int? InvUntSi { get; set; }
        public int? SalOprSi { get; set; }
        public string SalOprTp { get; set; }
        public double? SalOprDefaultValue { get; set; }
        public decimal? SalOprInc { get; set; }
        public decimal? SalOprDec { get; set; }
        public decimal? SalRequestDPrcDec { get; set; }
        public decimal? SalRequestDPrcInc { get; set; }
        public decimal? SalRequestDSumTotal { get; set; }
        public decimal? SalRequestDPrcInc2 { get; set; }
        public decimal? SalRequestDPrcDec2 { get; set; }
        public int? SalOprSi2 { get; set; }
        public string SalOprTp2 { get; set; }
        public double? SalOprDefaultValue2 { get; set; }
        public double? SalRequestDSumPrcDec { get; set; }
        public double? SalRequestDSumPrcInc { get; set; }
        public int? SalOprSi3 { get; set; }
        public string SalOprTp3 { get; set; }
        public double? SalOprDefaultValue3 { get; set; }
        public double? SalRequestDPrcInc3 { get; set; }
        public double? SalRequestDPrcDec3 { get; set; }
        public string BatchNumberD { get; set; }
        public string InvGdsCu { get; set; }
        public string InvGdsTp { get; set; }
        public string InvUntCu { get; set; }
        public string InvUntTp { get; set; }
        public string SalOprCu { get; set; }
        public string SalOprCu2 { get; set; }
        public string SalOprCu3 { get; set; }
        public int SalRequestDSi { get; set; }
        public int? SalCustGrpSi { get; set; }
        public int? SalRequestHGood { get; set; }
        public int? SiAccM { get; set; }
        public double? SalRequestHPrcGift { get; set; }
        public string SalRequestHStmpTimeEdit { get; set; }
        public string SalRequestHStmpTime { get; set; }
        public int? SalvarietySi { get; set; }
        public int? SalDriverSi { get; set; }
        public string SalRequestHDriverName { get; set; }
        public string SalRequestHBarNo { get; set; }
        public string DescDriver { get; set; }
        public bool? SalRequestHLock { get; set; }
        public int? SalDlvrrSi { get; set; }
        public int? SalDrvrSi { get; set; }
        public int? SalRespSi { get; set; }
        public int? SalTypSi { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public string SalRequestHRcvMthd { get; set; }
        public string SalRequestHDlvLoc { get; set; }
        public string BatchNumberH { get; set; }
        public bool? SalRequestDGiftOk { get; set; }
        public double? SalRequestDTotalC { get; set; }
        public double? SalRequestDUntPrcC { get; set; }
        public int? CtbCurncySi { get; set; }
        public double? ExchangeRate { get; set; }
        public string InvBatchNumberCode { get; set; }
        public string SalTypCu { get; set; }
        public string SalTypTp { get; set; }
        public string SalRespTp { get; set; }
        public string SalDrvrTp { get; set; }
        public string CtbAddrsPobox { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsFax { get; set; }
        public string CtbAddrsModem { get; set; }
        public string CtbAddrsMobile { get; set; }
        public string CtbAddrsEmail { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public string CtbAddrsContact { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public string CtbAddrsCity { get; set; }
        public string CtbAddrsOstan { get; set; }
        public string CtbAddrsShahrestan { get; set; }
        public string SalRegionTp { get; set; }
        public int? SalRequestHCu2 { get; set; }
        public DateTime? SalRequestHStmpMdt { get; set; }
        public string SalRequestHStmpMus { get; set; }
        public DateTime? SalRequestHStmpCdt { get; set; }
        public string SalRequestHStmpCus { get; set; }
    }
}
