using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalCust
    {
        public int SalCustSi { get; set; }
        public string SalCustTp { get; set; }
        public int SalCustGrpSi { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? AccTSi { get; set; }
        public int? AccMSi { get; set; }
        public string SalCustCu { get; set; }
        public int? SalIntrmdSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public string SalIntrmdTp { get; set; }
        public int? SalCustStatusSi { get; set; }
        public int? SalBrnchSi { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public int? SalCustStLook { get; set; }
        public string SalCustUser { get; set; }
        public int? SalRegionSi { get; set; }
        public int? SalRegionPathSi { get; set; }
        public string SalRegionTp { get; set; }
        public string SalRegionPathTp { get; set; }
        public short? SalCustCorporateTyp { get; set; }
        public string SalCustCorporateTypTp { get; set; }
        public bool? SalCustActive { get; set; }
        public string CtbAddrsShahrestan { get; set; }
        public string CtbAddrsOstan { get; set; }
        public string CtbAddrsCity { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public string CtbAddrsAccountName { get; set; }
        public string CtbAddrsAccountNo { get; set; }
        public string CtbAddrsCode { get; set; }
        public string CtbAddrsBranch { get; set; }
        public string CtbAddrsBankName { get; set; }
        public string CtbAddrsActiveType { get; set; }
        public string CtbAddrsLicenseCode { get; set; }
        public int? CtbAddrsMtr { get; set; }
        public string CtbAddrsAdvetiseDesc { get; set; }
        public string CtbAddrsPersonSkill { get; set; }
        public int? Expr1 { get; set; }
        public string CtbAddrsOwn { get; set; }
        public bool? CtbAddrsAdvetise { get; set; }
        public string CtbAddrsPersonality { get; set; }
        public string CtbAddrsContact { get; set; }
        public double? CtbAddrsMajor { get; set; }
        public bool? CtbAddrsDefault { get; set; }
        public string CtbAddrsEmail { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public string CtbAddrsModem { get; set; }
        public string CtbAddrsFax { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsMobile { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsPobox { get; set; }
        public string CtbAddrsDesc { get; set; }
        public int? CtbAddrsSi { get; set; }
        public bool? CtbAddrsShowPrint { get; set; }
        public bool? CtbAddrsDefault2 { get; set; }
        public string CtbAddrsInterduced { get; set; }
        public string CtbAddrsDsFirst { get; set; }
        public string CtbAddrsRelated { get; set; }
        public string CtbAddrsEnterduced { get; set; }
        public string SalcustRelated { get; set; }
        public string SalcustContact { get; set; }
        public string SalcustPersonSkill { get; set; }
        public string SalcustEnterduced { get; set; }
        public string SalcustDsFirst { get; set; }
        public double? SalcustMajor { get; set; }
        public string SalcustOwn { get; set; }
        public string SalcustActiveType { get; set; }
        public bool? SalcustAdvetise { get; set; }
        public string SalcustLicenseCode { get; set; }
        public int? SalcustMtr { get; set; }
        public string SalcustAdvetiseDesc { get; set; }
        public string SalCustPursuitTp { get; set; }
        public bool? SalCustPursuit { get; set; }
        public int? SalCustDivision { get; set; }
        public string SalCustProduceNow { get; set; }
        public string SalCustReasongust { get; set; }
        public string SalCustDesc { get; set; }
        public string SalCustDateEnter { get; set; }
        public int? SalEnterducedSi { get; set; }
        public string SalcustJob { get; set; }
        public int? CtbCustVndrTypSi { get; set; }
        public string CtbCustVndrTypTp { get; set; }
        public string SalCustStatusTp { get; set; }
        public string SalCustDateSave { get; set; }
        public int? SalCustActiveTypSi { get; set; }
        public string SalCustActiveTypTp { get; set; }
        public string SalDivisionTp { get; set; }
        public int? SalDivisionSi { get; set; }
        public string SalEnterducedTp { get; set; }
        public bool? SalCustNeesSearch { get; set; }
        public string SalCustTitle { get; set; }
        public int? AccLcSi { get; set; }
        public int? AccLpSi { get; set; }
        public bool? SalCustBlackList { get; set; }
        public int? SalCountrySi { get; set; }
        public int? SalProvinceSi { get; set; }
        public int? SalCitySi { get; set; }
        public int? CtbAddrsNumber { get; set; }
        public string SalAdmitCustDateEnter { get; set; }
        public string SalAdmitCustDateSearch { get; set; }
        public bool? SalAdmitCustNotNeedSearch { get; set; }
        public string SalAdmitCustGoodsNeed { get; set; }
        public int? SalAdmitStatusSi { get; set; }
        public bool? SalAdmitCustNeedsGift { get; set; }
        public string SalAdmitCustDesc { get; set; }
        public string SalAdmitCustUtiliseDate { get; set; }
        public string AccLpCu { get; set; }
        public string AccLpTp { get; set; }
        public string AccLtCu { get; set; }
        public string AccLtTp { get; set; }
        public string AccLcCu { get; set; }
        public string AccLcTp { get; set; }
        public string AccLmCu { get; set; }
        public string AccLmTp { get; set; }
        public string SalCustUserPursueInsert { get; set; }
        public string SalCustUserPursueUpdate { get; set; }
    }
}
