using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalPreInvcH
    {
        public int SalPreInvcHSi { get; set; }
        public int? SalPreInvcHCu { get; set; }
        public string SalPreInvcHDs { get; set; }
        public string SalPreInvcHTp { get; set; }
        public short SalPreInvcHRfrncTyp { get; set; }
        public string SalPreInvcHReference { get; set; }
        public string SalPreInvcHDlvLoc { get; set; }
        public string SalPreInvcHRcvMthd { get; set; }
        public decimal SalPreInvcHPrcSumTotal { get; set; }
        public decimal SalPreInvcHPrcInc { get; set; }
        public decimal SalPreInvcHPrcDec { get; set; }
        public decimal SalPreInvcHPrcTotal { get; set; }
        public int SalCustSi { get; set; }
        public int? SalBrnchSi { get; set; }
        public int? SalTypSi { get; set; }
        public int? SalIntrmdSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public string SalIntrmdTp { get; set; }
        public string SalTypCu { get; set; }
        public string SalTypTp { get; set; }
        public string SalCustTp { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsPobox { get; set; }
        public string CtbAddrsFax { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public byte SalPreInvcHStatus { get; set; }
        public short? SalPreInvcHExprTime { get; set; }
        public string SalPreInvcHExprDate { get; set; }
        public int? SalInvcHSi { get; set; }
        public string SalCustCu { get; set; }
        public int? SalRespSi { get; set; }
        public int? SalDrvrSi { get; set; }
        public int? SalDlvrrSi { get; set; }
        public string SalRespTp { get; set; }
        public string SalDrvrTp { get; set; }
        public string SalDlvrrTp { get; set; }
        public string SalPreInvcHStmpCus { get; set; }
        public DateTime? SalPreInvcHStmpCdt { get; set; }
        public string SalPreInvcHStmpMus { get; set; }
        public DateTime? SalPreInvcHStmpMdt { get; set; }
        public int? SalCustGrpSi { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? SalRegionSi { get; set; }
        public string SalRegionTp { get; set; }
        public int? InvInvtSi { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public decimal? SalPreInvcHPrcSumTotalC { get; set; }
        public double? SalPreInvcHPrcSumQty { get; set; }
        public decimal? SalExportPrmHPrcSumtotalC { get; set; }
        public string CtbAddrsCity { get; set; }
        public bool? CtbAddrsDefault { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public bool? SalPreInvcHLock { get; set; }
        public string CtbAddrsOstan { get; set; }
        public string CtbAddrsShahrestan { get; set; }
        public string SalRegionPathTp { get; set; }
        public int? SalRegionPathSi { get; set; }
        public int? SalpreinvchSndInv { get; set; }
        public int? InvDocHAccMSi { get; set; }
        public int? InvDocHCu { get; set; }
        public string AddrsSecondary { get; set; }
        public DateTime? SalPreInvcHDm { get; set; }
        public string BatchNumberH { get; set; }
        public int? SalPreInvcHCu2 { get; set; }
        public int? SalPreInvcHGoodSi { get; set; }
        public string SalPreInvcHGood { get; set; }
        public string SalPreInvcHBarNo { get; set; }
        public int? SalDriverSi { get; set; }
        public string SalDriverTp { get; set; }
        public string DescDriver { get; set; }
        public string TpProject { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public int? Salprint { get; set; }
        public int? SalvarietySi { get; set; }
        public string SalvarietyCu { get; set; }
        public string SalvarietyTp { get; set; }
        public string CtbAddrsEmail { get; set; }
        public string CtbAddrsModem { get; set; }
        public string CtbAddrsMobile { get; set; }
        public string SalDivisionTp { get; set; }
        public int? SalDivisionSi { get; set; }
        public int? SalpreInvcHRunNum { get; set; }
        public int? SalpreInvcHIno { get; set; }
        public bool? SalpreInvcHRunNumAccept { get; set; }
        public byte[] SignImage { get; set; }
        public int? SiAccM { get; set; }
        public string CuAcc { get; set; }
        public string TpAcc { get; set; }
        public string SalPreInvcHStmpTime { get; set; }
        public string SalPreInvcHStmpTimeEdit { get; set; }
    }
}
