using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class VwSalInvcH
    {
        public int SalInvcHSi { get; set; }
        public int? SalInvcHCu { get; set; }
        public string SalInvcHDs { get; set; }
        public DateTime? SalInvcHDm { get; set; }
        public string SalInvcHTp { get; set; }
        public short SalInvcHRfrncTyp { get; set; }
        public string SalInvcHReference { get; set; }
        public string SalInvcHDlvLoc { get; set; }
        public string SalInvcHRcvMthd { get; set; }
        public decimal SalInvcHPrcSumTotal { get; set; }
        public decimal? SalInvcHPrcSumTotalC { get; set; }
        public decimal SalInvcHPrcInc { get; set; }
        public decimal SalInvcHPrcDec { get; set; }
        public decimal SalInvcHPrcTotal { get; set; }
        public bool SalInvcHCancelled { get; set; }
        public int SalCustSi { get; set; }
        public int? SalBrnchSi { get; set; }
        public int? SalTypSi { get; set; }
        public int? SalIntrmdSi { get; set; }
        public int? InvInvtSi { get; set; }
        public string SalIntrmdCu { get; set; }
        public string SalIntrmdTp { get; set; }
        public string SalTypCu { get; set; }
        public string SalTypTp { get; set; }
        public string SalCustTp { get; set; }
        public string SalBrnchCu { get; set; }
        public string SalBrnchTp { get; set; }
        public string InvInvtCu { get; set; }
        public string InvInvtTp { get; set; }
        public string CtbAddrsCity { get; set; }
        public string CtbAddrsTel { get; set; }
        public string CtbAddrsZipcode { get; set; }
        public string CtbAddrsPobox { get; set; }
        public string CtbAddrsOstan { get; set; }
        public string CtbAddrsShahrestan { get; set; }
        public string CtbAddrsFax { get; set; }
        public string CtbAddrsAddrs { get; set; }
        public int? SalCustAccMSi { get; set; }
        public int? SalCustAccTSi { get; set; }
        public int? SalInvcHCu2 { get; set; }
        public bool SalInvcHAccDoc { get; set; }
        public bool SalInvcHPrcRcvd { get; set; }
        public string SalInvcHStmpCus { get; set; }
        public DateTime? SalInvcHStmpCdt { get; set; }
        public string SalInvcHStmpMus { get; set; }
        public DateTime? SalInvcHStmpMdt { get; set; }
        public string SalCustCu { get; set; }
        public string SalRespTp { get; set; }
        public string SalDlvrrTp { get; set; }
        public int? SalRespSi { get; set; }
        public int? SalDrvrSi { get; set; }
        public int? SalDlvrrSi { get; set; }
        public int? SalCustGrpSi { get; set; }
        public int? InvDocHSi { get; set; }
        public int? InvDocHAccMSi { get; set; }
        public bool? SalInvcHLock { get; set; }
        public int? InvDocHCu { get; set; }
        public string InvDocHDs { get; set; }
        public bool? InvDocHDefinite { get; set; }
        public int? SalRegionSi { get; set; }
        public string SalRegionTp { get; set; }
        public string SalCustGrpCu { get; set; }
        public string SalCustGrpTp { get; set; }
        public int? SalCustStatusSi { get; set; }
        public string SalDrvrTp { get; set; }
        public string SalDrvrTel { get; set; }
        public string SalDrvrAdrs { get; set; }
        public byte[] SalDrvrPhoto { get; set; }
        public int? AccLmSi { get; set; }
        public int? AccLtSi { get; set; }
        public int? SalCancleSi { get; set; }
        public int? SalGiftInvGdsSi { get; set; }
        public decimal? SalInvcHGiftTotal { get; set; }
        public int? SalContractHSi { get; set; }
        public int? Salprint { get; set; }
        public int? SalContractHCu { get; set; }
        public string CtbAddrsEconamical { get; set; }
        public int? SalInvcHDsMonth { get; set; }
        public int? SalPreinvcHSi { get; set; }
        public int? SalPreInvcHCu { get; set; }
        public string SalPreInvcHDs { get; set; }
        public string SalInvcHDsMonthTp { get; set; }
        public bool? CtbAddrsDefault { get; set; }
        public string CtbAddrsNatCode { get; set; }
        public string SalRegionPathTp { get; set; }
        public int? SalRegionPathSi { get; set; }
        public int? AccLmSi2 { get; set; }
        public byte? SalIntrmdValueTyp { get; set; }
        public decimal? SalIntrmdDefaultValue { get; set; }
        public string SalCancleTp { get; set; }
        public string BarNumber { get; set; }
        public string DescDriver { get; set; }
        public int? SalInvcHGood { get; set; }
        public string SalInvcHGoodTp { get; set; }
        public string AddrsSecondary { get; set; }
        public int? SalPreInvchSalExportPrmHCu { get; set; }
        public int? SalPreInvchSalExportPrmHDs { get; set; }
        public string SalInvcHPrcRcvdDt { get; set; }
        public double? SalInvcHIntrmdPrc { get; set; }
        public string SalInvcHBarNo { get; set; }
        public int? SalDriverSi { get; set; }
        public string AccLmCu { get; set; }
        public string AccLmTp { get; set; }
        public string AccLtCu { get; set; }
        public string AccLtTp { get; set; }
        public short? SalCustCorporateTyp { get; set; }
        public string SalCustTitle { get; set; }
        public string SalCustCorporateTypTp { get; set; }
        public string SalinvcHCarNo { get; set; }
        public string SalInvcHPostCode { get; set; }
        public string SalInvcHCodeSharestan { get; set; }
        public string SalInvcHTel { get; set; }
        public string SalInvcHAddrsPur { get; set; }
        public string SalInvcHNamePur { get; set; }
        public string SalInvcHIno { get; set; }
        public string SalInvcHNationalCode { get; set; }
        public string SalInvcHFamilyPur { get; set; }
        public decimal? InvDocDTotal { get; set; }
        public string CtbAddrsModem { get; set; }
        public string CtbAddrsEmail { get; set; }
        public string CtbAddrsMobile { get; set; }
        public decimal? SalDocVchrDebit { get; set; }
        public decimal? SalDocVchrCredit { get; set; }
        public int? SalCustDivision { get; set; }
        public string SalDivisionTp { get; set; }
        public int? SiAccM { get; set; }
        public string SalvarietyCu { get; set; }
        public int? SalvarietySi { get; set; }
        public string SalvarietyTp { get; set; }
        public bool? SalInvcHTrnsferDb { get; set; }
        public string InvInvtTp2 { get; set; }
        public double? SalInvcHSumGrantCust { get; set; }
        public double? SalInvcHSumGrantIntrmd { get; set; }
        public int? SalCustActiveTypSi { get; set; }
        public int? CtbCustVndrTypSi { get; set; }
        public int? SalEnterducedSi { get; set; }
        public int? SalDivisionSi { get; set; }
        public int? SalCitySi { get; set; }
        public int? SalProvinceSi { get; set; }
        public int? CtbAddrsNumber { get; set; }
        public int? AccLcSi { get; set; }
        public int? AccLpSi { get; set; }
        public int? SalIntrmdSiCust { get; set; }
        public string SalIntrmdCuCust { get; set; }
        public string SalIntrmdTpCust { get; set; }
        public int? SiCost { get; set; }
        public string SalDriverTp { get; set; }
        public double? SalDlvrrPercent { get; set; }
        public string SalInvcHStmpTime { get; set; }
        public string SalInvcHStmpTimeEdit { get; set; }
        public string SalDlvrrTpEn { get; set; }
        public string TpCost { get; set; }
    }
}
