using System;
using System.Collections.Generic;

namespace Data.Models.DB
{
    public partial class حقوقودستمزد4500گزارشپرسنلبههمراهعواملحکمي
    {
        public string تاريخشروعحکم { get; set; }
        public string تاريخاتمامحکم { get; set; }
        public string شمارهحکم { get; set; }
        public bool? حکمفعال { get; set; }
        public string کدپرسنلي { get; set; }
        public string نامپرسنل { get; set; }
        public decimal? کمکهزينهاولادطبقحکم { get; set; }
        public decimal? کمکهزينهخواروبار { get; set; }
        public decimal? کمکهزينهخواروبارطبقحكم { get; set; }
        public decimal? کمکهزينهسوخت { get; set; }
        public decimal? کمکهزينهسوختطبقحکم { get; set; }
        public decimal? کمکهزينهمسكن { get; set; }
        public decimal? کمکهزينهمسكنطبقحكم { get; set; }
        public decimal? اضافهكارثابت { get; set; }
        public decimal? اضافهكارثابتطبقحكم { get; set; }
        public decimal? افزايشسنواتي { get; set; }
        public decimal? ايابوذهاب { get; set; }
        public decimal? ايابوذهابطبقحكم { get; set; }
        public decimal? بازخريدخدمت { get; set; }
        public decimal? بازخريدخدمتبهازايهرسالروز { get; set; }
        public decimal? بازخريدخدمتمحاسبهشود { get; set; }
        public decimal? بازخريدمرخصي { get; set; }
        public decimal? بستانكاريازقبل { get; set; }
        public decimal? بيمه { get; set; }
        public decimal? بيمه30درصد { get; set; }
        public decimal? بيمهبيكاري3 { get; set; }
        public decimal? بيمهتكميلي { get; set; }
        public decimal? بيمهسهمكارفرما { get; set; }
        public decimal? پاداش { get; set; }
        public decimal? پورسانت { get; set; }
        public decimal? تعدادروزهايغيبت { get; set; }
        public decimal? تعدادروزهايكاركرد { get; set; }
        public decimal? تعدادروزهايكاريماه { get; set; }
        public decimal? تعدادفرزند { get; set; }
        public decimal? تعدادكلروزهايكاركرددرگذشته { get; set; }
        public decimal? تعدادماموريت { get; set; }
        public decimal? تعدادماههايكاركرد { get; set; }
        public decimal? تفاوتتطبيق { get; set; }
        public decimal? جمعکلماندهحقوقومزاياينقديوغيرنقديعيديوپاداش { get; set; }
        public decimal? جمعکلمبالغپرداختيتخصيصيغيرنقدي { get; set; }
        public decimal? جمعکلمبالغپرداختيهاتخصيصينقدي { get; set; }
        public decimal? جمعتعدادروزهايكاركرد { get; set; }
        public decimal? جمعحقوقومزايا { get; set; }
        public decimal? جمعحقوقومزاياينقديومشمولمالياتقبلي { get; set; }
        public decimal? جمعروزهايكاركرددردورههايمحاسبهشده { get; set; }
        public decimal? جمعكسورات { get; set; }
        public decimal? جمعكلمبالغتخصيصغيرنقديقبلي { get; set; }
        public decimal? جمعمالياتمتعلقهقبلي { get; set; }
        public decimal? جمعمرخصيهايرفته { get; set; }
        public decimal? حداقلحقوقروزانه { get; set; }
        public decimal? حقاتومبيلغيرنقدي { get; set; }
        public decimal? حقجذب { get; set; }
        public decimal? حقجذبطبقحكم { get; set; }
        public decimal? حقشاغل { get; set; }
        public decimal? حقشاغلطبقحکم { get; set; }
        public decimal? حقماموريت { get; set; }
        public decimal? حقمسکنغيرنقدي { get; set; }
        public decimal? حقمسئوليتوسرپرستي { get; set; }
        public decimal? حقمسئوليتوسرپرستيطبقحكم { get; set; }
        public decimal? حقنهار { get; set; }
        public decimal? حقوقثابت { get; set; }
        public decimal? حقوقروزانه { get; set; }
        public decimal? حقوقمبنا { get; set; }
        public decimal? حقوقومزايايغيرمستمر { get; set; }
        public decimal? حقوقومزايايمستمر { get; set; }
        public decimal? خريدمحصولاتشرکت { get; set; }
        public decimal? درآمدمشمولمالياتپسازکسرمعافيتموضوعماده84 { get; set; }
        public decimal? درصدضريبماليات { get; set; }
        public decimal? درصدنوبتكاري { get; set; }
        public decimal? درصورتتعلقنگرفتنبيمهعدد1راواردكنيد { get; set; }
        public decimal? درصورتتعلقنگرفتنمالياتعدد1راواردكنيد { get; set; }
        public decimal? درصورتقرارگرفتندرمناطقمحرومعدد1راواردكنيد { get; set; }
        public decimal? ذخيرهبازخريدخدمتامسال { get; set; }
        public decimal? ذخيرهسنواتدرسالهايگذشته { get; set; }
        public decimal? روزمبناينهار { get; set; }
        public decimal? ساعتاضافهكاريتعطيلي { get; set; }
        public decimal? ساعتاضافهكاريعادي { get; set; }
        public decimal? ساعتشبكاري { get; set; }
        public decimal? ساعتكسركار { get; set; }
        public decimal? سايرپرداختهايماهجاري { get; set; }
        public decimal? سايرپرداختيها { get; set; }
        public decimal? سايركسورات { get; set; }
        public decimal? سايرمزايا { get; set; }
        public decimal? سايرمعافيتهابهغيرازمعافيتموضوعماده84 { get; set; }
        public decimal? سختيكار { get; set; }
        public decimal? سختيكارطبقحكم { get; set; }
        public decimal? سقفبيمهروزانه { get; set; }
        public decimal? سقفعيديسالانه { get; set; }
        public decimal? شمارهماهقبل { get; set; }
        public decimal? صندوقپسانداز { get; set; }
        public decimal? ضريبتخصصيويژه { get; set; }
        public decimal? ضريبتخصصيويژهطبقحکم { get; set; }
        public decimal? عيدي { get; set; }
        public decimal? عيديوپاداش { get; set; }
        public decimal? فوقالعادهدوريازمرکز { get; set; }
        public decimal? فوقالعادهدوريازمرکزطبقحکم { get; set; }
        public decimal? فوقالعادهشرايطمحيطکار { get; set; }
        public decimal? فوقالعادهشرايطمحيطکارطبقحکم { get; set; }
        public decimal? قابلپرداخت { get; set; }
        public decimal? قابلپرداختعيدي { get; set; }
        public decimal? كارانه { get; set; }
        public decimal? كارانهطبقحكم { get; set; }
        public decimal? كمكهزينهبنطبقحكم { get; set; }
        public decimal? كمكهزينهاولاد { get; set; }
        public decimal? كمكهزينهبن { get; set; }
        public decimal? مالياتپرداختيازابتدايسال { get; set; }
        public decimal? مالياتعيدي { get; set; }
        public decimal? مالياتقابلپرداختپسازاعمالمعافيتموضوعماده92 { get; set; }
        public decimal? مالياتقابلپرداختماهجاري { get; set; }
        public decimal? ماندهپرداختيتخصيصينقديپسازکسرمعافيتماده91 { get; set; }
        public decimal? ماندهپرداختيتخصيصيغيرنقديپسازکسرمعافيتموضوعبند13ماده91 { get; set; }
        public decimal? ماندهسنوات { get; set; }
        public decimal? ماندهمرخصي { get; set; }
        public decimal? ماندهمرخصيساليانه { get; set; }
        public decimal? ماندهوام { get; set; }
        public decimal? مبلغاضافهكارتعطيلي { get; set; }
        public decimal? مبلغاضافهكاريعادي { get; set; }
        public decimal? مبلغپرداختيتخصيصيغيرنقدي { get; set; }
        public decimal? مبلغشبكاري { get; set; }
        public decimal? مبلغعيديمشمولماليات { get; set; }
        public decimal? مبلغقابلاحتساببابتاتومبيل { get; set; }
        public decimal? مبلغقابلاحتساببابتمسکن { get; set; }
        public decimal? مبلغكسركار { get; set; }
        public decimal? مبلغنوبتكاري { get; set; }
        public decimal? محاسبهعيديدراينماهصورتپذيرد { get; set; }
        public decimal? مرخصيرفتهدراينماه { get; set; }
        public decimal? مرخصيساليانه { get; set; }
        public decimal? مرخصيهايرفتهازابتدايسال { get; set; }
        public decimal? مرخصيهايرفتهدرماه { get; set; }
        public decimal? مزايايمشمولبيمه { get; set; }
        public decimal? مساعده { get; set; }
        public decimal? مشمولبيمه { get; set; }
        public decimal? مشمولبيمهبااحتسابسقفبيمه { get; set; }
        public decimal? مشمولماليات { get; set; }
        public decimal? مشمولمالياتازابتدايسال { get; set; }
        public decimal? معافيتماده91 { get; set; }
        public decimal? معافيتمالياتعيدي { get; set; }
        public decimal? نرخشبكاري { get; set; }
        public decimal? نرخنوبتكاري { get; set; }
        public decimal? نهاريطبقحكم { get; set; }
        public decimal? هزينهسوخت { get; set; }
        public decimal? هزينهسوختطبقحکم { get; set; }
        public decimal? هزينهماموريت { get; set; }
        public decimal? وام { get; set; }
        public decimal? وضعيتاستفادهازاتومبيل { get; set; }
        public decimal? وضعيتاستفادهازمسکن { get; set; }
        public decimal? وضعيتتاهل { get; set; }
    }
}
